min_trust_level:
  default: 0
  type: enum
  description: "Minimum required trust level for the button to be visible in the post menu"
  choices:
    - 0
    - 1
    - 2
    - 3
    - 4
svg_icons:
  default: ''
  type: 'list'
  list_type: 'compact'
  description: 'List of FontAwesome 5 icons used in this theme component'
